### PR TITLE
[BrokenLinksH2] fixing broken link

### PR DESCRIPTION
**Pull request by StephenBrentPeters**

### CODE REVIEW

**Comment by StephenBrentPeters** [comment]
@ShawnJackson odd error message here, not sure what to do with it.

**Comment by ShawnJackson** [comment]
@StephenBrentPeters - Closing and reopening the PR might clear it up.

**Comment by StephenBrentPeters** [comment]
Closing and reopening as suggested by Shawn

**Comment by StephenBrentPeters** [comment]
**Global effort to fix broken links**

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Pull request merged**
